import { StyleSheet } from "react-native";
export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#eaf8fbff',
        alignItems: 'center',
    },
    cabecera:{
        width: '100%',
        height: '12%',
        backgroundColor:'#C0C4D3',
        borderBottomColor:'#006AFF',
        borderBottomWidth: 4,
        flexDirection:'row',
    },
    tituloContent:{
        width:'50%',
        justifyContent: 'flex-start',
    },
    logoContent:{
        width:'50%',
        justifyContent:'flex-end',
        alignItems: 'flex-end',
    },
    titulo:{
        fontSize: 25,
        marginLeft: 15,
        marginTop: 60,
        color: '#4CAA1D', 
    },
    logo:{
        width:65,
        height: 65,
        marginBottom:2,
        marginRight: 17,
    },
    footer:{
        // backgroundColor: '#e8e8e8ff',
        width: '100%',
        height: '10%',
        flexDirection: 'row',
        justifyContent:'space-around',
        alignItems: 'center',
        padding:15,
        paddingBottom: 30,
        marginTop: 20,
    },
    pantallaActualContainer:{
        width: '90%',
        height: 80,
        marginTop: 10,
        justifyContent:'center',
        alignItems: 'center',
        backgroundColor: '#C0D5F2',
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10,
        paddingBottom: 8,
        paddingLeft: 8,
        paddingTop: 20,
        borderBottomColor: '#E0EDFF',
        borderBottomWidth: 4,
        flexDirection: 'row',
        gap: 10,
    },
    textoPantalla:{
        color: 'gray',
        fontSize: 22,
        padding: 5,
        backgroundColor: '#E0EDFF',
        width: '80%',
        borderRadius: 10,
        textAlign: 'center',
        height: 40,
    
    },
    contenidoScreen:{
        backgroundColor:'#C0D5F2',
        width: '90%',
        borderRadius:10,
        borderTopColor:'#a8c0e2ff',
        borderTopWidth:2,
    },
})